# CodeArena Multi-Service Railway Deployment
# This project contains three services that should be deployed separately:
# 1. codearena-server (API backend)
# 2. codearena-client (React frontend)
# 3. codearena-execution (Code execution system)

[build]
builder = "nixpacks"
buildCommand = "npm install"
# Alternative: use Docker
# builder = "dockerfile"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# This is a multi-service application
# For production deployment, create separate Railway projects:
# 1. codearena-server (from server/ directory)
# 2. codearena-client (from client/ directory)  
# 3. codearena-execution (from execution-system/ directory)
#
# Each service has its own railway.toml configuration file.

# Service 1: API Backend
# Deploy from: server/
# Command: npm start
# Health check: /health

# Service 2: Frontend Client  
# Deploy from: client/
# Command: npm run serve
# Health check: /

# Service 3: Execution System
# Deploy from: execution-system/
# Command: node railway.js
# Health check: /health

# Environment Variables needed:
# - MONGODB_URI
# - SESSION_SECRET
# - GOOGLE_CLIENT_ID
# - GOOGLE_CLIENT_SECRET
# - FRONTEND_URL (for CORS)
# - API_URL (for client to connect to server) 