[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node railway.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production" 